version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: docker/go/Dockerfile
    ports:
      - '${DOCKER_APP_PORT}:${APP_PORT}'
    volumes:
      - ./:/var/www/cropler
      - ${IMAGE_STORAGE_PATH}:${APP_STORAGE_PATH}